### ISSUE TITLE
MVP's

### ISSUE THREAD

**Issue by simcha-c** [cindyytong/halcyon#1]
Auth:
- [x] this will be the signing up, logging in, logging out etc.
- [x] we'll also have to create the therapists accounts in this mvp. so we'll have two account creations. 1. patients and 2. therapists.

Matching to therapists:
- [x] when a patient signs up, the site will ask the user questions about preferences when it comes to therapists. I think you should ask the user the questions in this mvp. It has to do with matching the user to therapists. At this point, you'll have patient accounts and therapists account, so should be good.

Chats:
- [x] add a bullet point that this is instant chatting using web sockets.

Reviews:
- [ ] I dont want to do reviews for therapists. We could do feedback, but i thought we decided on notes for the therapists?

Great job!

**Comment by cindyytong** [comment]
@simcha-c Thank you for these notes! Re: reviews, I was trying to avoid designing a custom UI for a feature that didn't exist but see your point regarding the reviews. I'll stick with the original plan then and look at Evernote as reference.
